Sprint 11: добавление базы данных
UlyanaVasilieva/my-project-filmorate pull request #3
Opened 2023-08-09 08:54 UTC by UlyanaVasilieva

1) Добавила файл schema.sql, в котором описала создание таблиц, и data.sql
2) Добавила DAO для пользователя, фильма, рейтинга и жанра
3) Добавила новые контроллеры для рейтинга и жанра
4) Добавила интеграционные тесты на DAO

2023-08-09 12:28 UTC, PolnySkvorets commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    private void initLikesIfNull(Film film) {
здесь ты можешь сразу передавать массив лайков

2023-08-09 12:29 UTC, PolnySkvorets commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +        getGenreById(id);
Нет значения, которому присваивается результат выполнения метода

2023-08-09 12:33 UTC, PolnySkvorets commented on src/test/java/ru/yandex/practicum/filmorate/dao/FilmDbStorageTest.java
> +@RequiredArgsConstructor(onConstructor_ = @Autowired)
(onConstructor_ = @Autowired) - это можно использовать, чтобы показать явно, на на практике не обязательно, у тебя будет один конструктор, Spring  по умолчанию внедряет зависимости в единственный конструктор в классе

2023-08-09 12:38 UTC, PolnySkvorets commented on src/test/java/ru/yandex/practicum/filmorate/dao/FilmDbStorageTest.java
> +            .id(++filmId)
Можно не изменять filmId, так как после теста он удаляет созданную запись из базы

2023-08-09 12:39 UTC, PolnySkvorets requested changes
Привет! Очень хорошая работа: добавлены нужные аннотации, проверки, схема базы отлично описана. Есть парочка небольштх замечаний.

2023-08-09 14:02 UTC, UlyanaVasilieva commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    private void initLikesIfNull(Film film) {
Этот метод еще устанавливает лайки для фильма. Если его изменить, тогда получится такая вложенность методов: film.setLikes(initLikesIfNull(film.getLikes())); Не будет ли удобнее для чтения кода оставить прошлый вариант?

2023-08-09 14:26 UTC, UlyanaVasilieva commented on src/main/java/ru/yandex/practicum/filmorate/storage/genre/GenreDbStorage.java
> +        getGenreById(id);
Спасибо за замечание, добавляю методы в контроллеры

2023-08-09 14:35 UTC, UlyanaVasilieva commented on src/test/java/ru/yandex/practicum/filmorate/dao/FilmDbStorageTest.java
> +@RequiredArgsConstructor(onConstructor_ = @Autowired)
В ТЗ был дан такой пример теста, поэтому я использовала этот параметр. Если его сейчас убираю, то получаю ParameterResolutionException. Скажи, пожалуйста, что в этом случае нужно сделать?

2023-08-09 14:45 UTC, UlianaKomissarova commented on src/test/java/ru/yandex/practicum/filmorate/dao/FilmDbStorageTest.java
> +            .id(++filmId)
В файле src/main/java/ru/yandex/practicum/filmorate/storage/user/UserDbStorage.java в методе create происходит автогенерация id, из-за чего мне приходится делать это в тесте. Метод create взяла из статьи, которая прилагается нам в ТЗ про операции CRUD.

2023-08-11 05:24 UTC, PolnySkvorets commented on src/test/java/ru/yandex/practicum/filmorate/dao/FilmDbStorageTest.java
> +            .id(++filmId)
Окей, если так, пусть останется. Это выглядит немного странным, что тесты зависят друг от друга немного

2023-08-11 05:28 UTC, PolnySkvorets commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +    private void initLikesIfNull(Film film) {
Да, оставь прошлый вариант в этом случае

2023-08-11 05:28 UTC, PolnySkvorets commented on src/test/java/ru/yandex/practicum/filmorate/dao/FilmDbStorageTest.java
> +@RequiredArgsConstructor(onConstructor_ = @Autowired)
Да, оставь старую аннотацию, в тестах работает только с ней

2023-08-12 16:27 UTC, PolnySkvorets approved these changes
Замечания исправлены. Крутая работа!

2023-08-28 07:01 UTC, merged